

services:


  database:
    image: postgres:16-alpine
    container_name: database
    hostname: local_database
    restart: always
    env_file:
      - .env
    ports:
      - "6655:5432"
    volumes:
      - postgres_datastorage:/var/lib/postgresql/data
    networks:
      - main_network

  backend_api:
    build:
      dockerfile: Dockerfile
      context: backend_api
    container_name: Backend_api
    hostname: backend_api
    restart: always
    env_file:
      - .env
    volumes:
      - ./backend_api/app:/app
    ports:
      - "9999:9999"
    command: |
      sh -c "
      uvicorn main:app --port=9999 --host=0.0.0.0 --reload
      "
    networks:
      - main_network


  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    container_name: frontend
    hostname: frontend
    restart: always
    env_file:
      - .env
    volumes:
      - ./frontend/app:/app
    ports:
      - "12345:12345"
    command: |
      sh -c "
      uvicorn main:app --port=12345 --host=0.0.0.0 --reload
      "
    networks:
      - main_network

  nginx_project:
    image: nginx:alpine
    container_name: nginx_project
    restart: always
    ports:
      - "80:80"
    networks:
      - main_network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

networks:
  main_network:
    driver: bridge

volumes:
  postgres_datastorage:
    external: false
